# Generated by Django 5.2.8 on 2025-11-12 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginip',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loginip',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
