# Generated by Django 5.2.8 on 2025-11-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_loginip_city_loginip_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginip',
            name='city',
        ),
        migrations.RemoveField(
            model_name='loginip',
            name='country',
        ),
        migrations.AddField(
            model_name='loginip',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
