# Generated by Django 5.2.7 on 2025-11-13 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_remove_loginip_city_remove_loginip_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('client_company', models.CharField(max_length=200)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_phone', models.CharField(max_length=20)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('valid_until', models.DateField()),
                ('payment_terms', models.CharField(max_length=200)),
                ('salesperson', models.CharField(max_length=100)),
                ('products', models.JSONField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('validity', models.CharField(default='30 days', max_length=50)),
                ('delivery', models.CharField(default='Immediate', max_length=50)),
                ('warranty', models.CharField(blank=True, max_length=50)),
                ('shipping', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
