# Generated by Django 5.2.7 on 2025-11-15 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_quotation'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('counter', models.IntegerField()),
            ],
        ),
    ]
